export SPARK_LOCAL_DIRS=/tmp/spark
export SPARK_LOG_DIR=$SPARK_HOME/logs
export SPARK_MASTER_HOST=10.0.0.3
export SPARK_MASTER_PORT=7077
export SPARK_MASTER_WEBUI_PORT=8080
export SPARK_WORKER_PORT=8081
export SPARK_WORKER_WEBUI_PORT=8081
